"""Demo-mode app boot via Streamlit AppTest: start gate, provider, and data."""
import pandas as pd
from streamlit.testing.v1 import AppTest

from app.agent import _compute_kpis, _compute_new_lost, _compute_top_movers
from app.guardrails import BLOCK_MESSAGE, LOCK_MESSAGE


def _fake_result():
    df = pd.DataFrame({
        "CUSTOMER_NAME": ["Acme Lines", "Blue Corp"],
        "VOLUME": [100.0, 200.0], "GP": [1000.0, 2400.0],
        "MARGIN": [10.0, 12.0], "WON": [1, 2], "INQUIRIES": [2, 3], "LOST": [1, 1],
    })
    dims = ["CUSTOMER_NAME"]
    return {
        "kpis": _compute_kpis(df, df),
        "narrative": "GP was flat month over month.",
        "top_movers": _compute_top_movers(df, df, dims),
        "new_lost": _compute_new_lost(df, df, dims),
        "df_a": df, "df_b": df, "sql_a": "SELECT 1", "sql_b": "SELECT 1",
    }


_FAKE_META = {
    "month_a": "2026-02-01",
    "month_b": "2026-03-01",
    "dimensions": ["CUSTOMER_NAME"],
    "provider": "openai",
    "model": None,
}


def _boot(**session_state):
    at = AppTest.from_file("app/main.py", default_timeout=60)
    for key, val in session_state.items():
        at.session_state[key] = val
    at.run()
    return at


def test_start_gate_blocks_until_started():
    at = _boot()
    assert not at.exception
    # The start screen is showing, so the app controls are not mounted yet.
    assert len(at.selectbox) == 0
    assert any(button.label == "Start" for button in at.button)
    assert len(at.text_input) == 0


def test_app_renders_after_start_with_no_provider_controls():
    at = _boot(demo_started=True)
    assert not at.exception
    # months came from DuckDB demo data
    labels = [sb.label for sb in at.selectbox]
    assert "Month A (baseline)" in labels and "Month B (compare to)" in labels
    # newest dataset month (2026-06) is hidden in demo; defaults are Apr vs May
    month_options = at.selectbox[0].options
    assert "2026-06-01" not in month_options and len(month_options) == 17
    assert month_options[0] == "2026-05-01"
    month_a = next(sb for sb in at.selectbox if sb.label == "Month A (baseline)")
    month_b = next(sb for sb in at.selectbox if sb.label == "Month B (compare to)")
    assert month_a.value == "2026-04-01"
    assert month_b.value == "2026-05-01"
    # provider controls are gone
    assert len(at.radio) == 0
    assert all("model" not in (ti.label or "").lower() for ti in at.text_input)
    # nothing on the page mentions the provider
    page_text = " ".join(str(getattr(el, "value", "")) for el in at.markdown)
    assert "openai" not in page_text.lower() and "gpt" not in page_text.lower()


def test_locked_session_hides_chat_input_and_warns():
    at = _boot(
        demo_started=True,
        gr_locked=True,
        comparison_result=_fake_result(),
        compare_meta=dict(_FAKE_META),
    )
    assert not at.exception
    # results section rendered (chat section is only reachable with a result)
    assert any("Results:" in str(el.value) for el in at.subheader)
    # locked: no chat input, and the lock warning is shown
    assert len(at.chat_input) == 0
    assert any(LOCK_MESSAGE in str(w.value) for w in at.warning)


def test_unlocked_session_with_results_shows_chat_input():
    at = _boot(
        demo_started=True,
        comparison_result=_fake_result(),
        compare_meta=dict(_FAKE_META),
    )
    assert not at.exception
    assert any("Results:" in str(el.value) for el in at.subheader)
    assert len(at.chat_input) == 1
    assert not any(LOCK_MESSAGE in str(w.value) for w in at.warning)


def test_leaking_narrative_is_filtered_on_render():
    result = _fake_result()
    result["narrative"] = "This analysis was generated by OpenAI GPT-4."
    at = _boot(
        demo_started=True,
        comparison_result=result,
        compare_meta=dict(_FAKE_META),
    )
    assert not at.exception
    page_text = " ".join(str(getattr(el, "value", "")) for el in at.markdown)
    assert "openai" not in page_text.lower()
    assert "gpt" not in page_text.lower()
    assert BLOCK_MESSAGE in page_text
